### PR TITLE
[Strava Integration] Manually created activities use different activity types than uploaded activities + unit tests 

### PR DESCRIPTION
**Pull request by FJBDev**

### CODE REVIEW

**Comment by FJBDev** [comment]
@wolfgang-ch  I had marked this PR as `draft` because it was not ready to be merged and this is why the build today fails (unit test issue). I will create a new PR when I have a fix for the build

**Comment by wolfgang-ch** [comment]
I reviewed and merged your branch in Eclipse (which closed automatically this PR after I commited it) and saw the draft label afterwards

**Comment by FJBDev** [comment]
That's ok, I created the PR thinking I was done because the unit tests were successful locally but then the build failed so I switched to draft.

**Comment by FJBDev** [comment]
@wolfgang-ch 
I have fixed the unit tests and verified that the build is now successful. My PR is ready to be merged [here](https://github.com/mytourbook/mytourbook/pull/437)

**Pull request merged**
