### PR TITLE
[Integration Tests] Adding WorldWeatherOnline tests

### PR DESCRIPTION
**Pull request by FJBDev**
@wolfgang-ch 
Now this is really cool, my code modifications is compared exactly to the latest main at all times 👍 

What is also nice is that even though I have access to your repo, my PRs are still blocked until you review and approve

image

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
With the move of MT to a GitHub organisation, now I can commit into the main branch again as before without creating a PR and could also merge your PR's without a review

image

**Comment by wolfgang-ch** [comment]
You have commited very often into the branches in your git repo but when you now can commit into "my" repo, you should reduce the number of commits otherwise (I think) all commits will be kept in the FJBDev branch even when I squash them when merged into the main branch.

**Comment by wolfgang-ch** [comment]
> You have commited very often into the branches in your git repo but when you now can commit into "my" repo, you should reduce the number of commits otherwise (I think) all commits will be kept in the FJBDev branch even when I squash them when merged into the main branch.

->You should also squash your commits (as I do when merging a PR) when you create a commit into my repo

**Comment by FJBDev** [comment]
> You have commited very often into the branches in your git repo but when you now can commit into "my" repo, you should reduce the number of commits otherwise (I think) all commits will be kept in the FJBDev branch even when I squash them when merged into the main branch.

You can't select "Squash and Merge" in the drop down below just like previously ?
I think it would still be useful to use Squash and Merge because even if I do a single commit, after you review, you might ask me to do more changes and then I will do another (or more) commits

**Comment by FJBDev** [comment]
@wolfgang-ch 
It seems that you can configure PRs to be [squashed automatically](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests) ?

**Comment by wolfgang-ch** [comment]
> > You have commited very often into the branches in your git repo but when you now can commit into "my" repo, you should reduce the number of commits otherwise (I think) all commits will be kept in the FJBDev branch even when I squash them when merged into the main branch.
> 
> You can't select "_Squash and Merge_" in the drop down below just like previously ?

Yes I can

> ->You should also squash your commits (as I do when merging a PR) when you create a commit into my repo

All your "small" commit comments should not be in my git history...
(this screenshot is from your repo)
image

...like it is already now

(this screenshot is from my repo)
image

It is like when you create a PR which you are doing when a feature is completed, then you should sqash your commits and sync **only this single squashed commit** with my repo

**Comment by FJBDev** [comment]
> All your "small" commit comments should not be in my git history... (this screenshot is from your repo) 

I have fixed it so that only 1 commit shows now in this PR
image


> It is like when you create a PR which you are doing when a feature is completed, then you should sqash your commits and sync **only this single squashed commit** with my repo

Sure but keep in mind that when you review my PRs, i will have to do some code fixes and some more commits that you will have to squash when you merge my finalized PR. Because those small commits will appear in FJBDev, I will overwrite FJBDev with your main to start with a "clean plate"

**Comment by wolfgang-ch** [comment]
> is it really necessary for me to squash my commits since you will be the one squashing the very last commit that goes to `main` ?

You can do anything as long as your small commit's do not appear in my git history

There is another branch from you in my git repo

image

Maybe your branches `FJBDev...` could be renamed into `fb-...` it would be easier for me to type the name :-) and would be aligned to my new branch naming structure where I cleaned up the branch names?

@telemaxx 
Maybe your branches `map25...` could also be renamed into `tm-...` or something else?

**Comment by wolfgang-ch** [comment]
> Sure but keep in mind that when you review my PRs, i will have to do some code fixes and some more commits that you will have to squash when you merge my finalized PR into `main`.

For me there is no need to squash commits, when there is only one commit for the PR and one for each review fix. 

I think it may be necessary for you to create squash commit's when you create a commit for a PR or a review fix.

**Comment by telemaxx** [comment]
> 
> @telemaxx Maybe your branches `map25...` could also be renamed into `tm-...` or something else?

yes we can change that name. eg tm-map25
@wolfgang-ch:  you can choose the name, i clone that than in my fork.

@wolfgang-ch , @FJBDev : you are doing cool new github stuff. 
`organisation,`, `actions` and `squash` that is all new to me. i have to read about that.

`actions` seems to be very interesting to me. good for testing.
last time i merged main to main in my branch, i saw that actions where running.
At the end there was an build error, but merge was ok
now i saw that the automated builds are also ok the last 3 times. cool.

**Comment by wolfgang-ch** [comment]
>`organisation`, `actions` and `squash` that is all new to me

me too

**Comment by FJBDev** [comment]
> There is another branch from you in my git repo
> 
I just deleted this branch `fb-weathertests`

> Maybe your branches `FJBDev...` could be renamed into `fb-...` it would be easier for me to type the name :-) and would be aligned to my new branch naming structure where I cleaned up the branch names?
> 
I have renamed to `fb-improvements` to align with your `ws-improvements`

**Comment by FJBDev** [comment]
> For me there is no need to squash commits, when there is only one commit for the PR and one for each review fix.

I agree but it's rare that my PRs are perfect and don't require a fix 😄 

> I think it may be necessary for you to create squash commit's when you create a commit for a PR or a review fix.

I will create squash commits. But what if I create a PR with a squash commit and then at the last minute I find a little bug to fix, do I wait for the next PR ? or do I commit the bugfix expecting you to squash my entire PR ?

**Comment by wolfgang-ch** [comment]
> > I think it may be necessary for you to create squash commit's when you create a commit for a PR or a review fix.
> 
> I will create squash commits. But what if I create a PR with a squash commit and then at the last minute I find a little bug to fix, do I wait for the next PR ? or do I commit the bugfix expecting you to squash my entire PR ?

New commits for last fixes are OK

**Pull request closed without merging**
