### PR TITLE
[Fitlog/Fitlogex] Compute the average power when power data is provided but average power value is not

### PR DESCRIPTION
**Pull request by FJBDev**

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
@FJBDev When you created this PR, then there was also a PR which you merged in fj-improvements, So there were 2 PR's which I had to review. I discovered, that (maybe since Eclipse 2022-6 because Eclipse PR's are now hosted on Github) there is a new feature to fetch PR's directly into Eclipse (to do the review in Eclipse), you just have to copy the url into the clipboard and all the dialog is filled in automatically. 

Maybe we can also go this way so you don't have to merge into fj-improvements.

image

**Comment by FJBDev** [comment]
@wolfgang-ch So you're saying that I can now do directly a PR from a branch in my repo to your main branch ?

**Comment by wolfgang-ch** [comment]
> ... that I can now do directly a PR from a branch in my repo to your main branch ?

You already did this, one of these merges were not in `fb-improvements`

image

**Comment by FJBDev** [comment]
> You already did it, one of these two merges were not in `fb-improvements`
> 
> image

Correct, I did that at the time because I had already another PR open using `fb-improvements`

**Pull request merged**
