### PR TITLE
UI Tests improvements

### PR DESCRIPTION
**Pull request by FJBDev**
UI tests enhancements in order for them to be independent and to run on any machine in any given timezones

@wolfgang-ch Following up on your comment [here](https://github.com/mytourbook/mytourbook/commit/2647dbb8a610709bb728773dc14ec40c64fd552a#r128511019) that you don't seem to be able to run the UI tests on your local machine, I have made some changes and enhancements hoping that anyone would be able to run them on their machine.
Can you give it a try and let me know if it works now ?

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
> UI tests enhancements in order for them to be independent and to run on any machine in any given timezones
> 
> @wolfgang-ch Following up on your comment [here](https://github.com/mytourbook/mytourbook/commit/2647dbb8a610709bb728773dc14ec40c64fd552a#r128511019) that you don't seem to be able to run the UI tests on your local machine, I have made some changes and enhancements hoping that anyone would be able to run them on their machine. Can you give it a try and let me know if it works now ?

Less errors 😄   [test-errors.txt](https://github.com/mytourbook/mytourbook/files/13062734/test-errors.txt)

image



This Export Tours dialog stays open very long while other test are running in the background UI

image

**Comment by FJBDev** [comment]
> Less errors 😄 [test-errors.txt](https://github.com/mytourbook/mytourbook/files/13062734/test-errors.txt)
That's better !
> 
> This **Export Tours** dialog stays open for a very long while other test are running in the background UI
> 
Do you get this issue every time you run the tests?
I saw it only once or twice but there was never an error in the log

**Comment by wolfgang-ch** [comment]
I repeated the test with the version which has the 23.10 tag in the git repo, now there are more errors and another dialog is displayed

[net.tourbook.ui.tests 1.xml.zip](https://github.com/mytourbook/mytourbook/files/13066564/net.tourbook.ui.tests.1.xml.zip)



[net.tourbook.ui.tests 2.xml.zip](https://github.com/mytourbook/mytourbook/files/13066568/net.tourbook.ui.tests.2.xml.zip)





2023-10-23 dialog 2

**Comment by FJBDev** [comment]
> image
> 
> This **Export Tours** dialog stays open for a very long while other test are running in the background UI
> 

I reproduced the issue and this is why the **Export Tours** dialog stays open.

It seems that [this line](https://github.com/mytourbook/mytourbook/blob/49b73da7a01d06cedafaaf2f83a4374814f04b96/bundles/net.tourbook.export/src/net/tourbook/export/DialogExportTour.java#L1453) from [your commit](https://github.com/mytourbook/mytourbook/commit/ad94f22cfd19e3b41458ac137a29b17ce158fdc5) is creating the NPE

If I comment it, the test for **Export Tours** works. Are you seeing the same thing ?

image



```
java.lang.NullPointerException: Cannot read field "y" because "popupSize" is null
	at net.sf.swtaddons.autocomplete.combo.AutocompleteCombo.saveState(AutocompleteCombo.java:103)
	at net.tourbook.export.DialogExportTour.saveState(DialogExportTour.java:1453)
	at net.tourbook.export.DialogExportTour.close(DialogExportTour.java:329)
	at org.eclipse.jface.dialogs.Dialog.okPressed(Dialog.java:948)
	at net.tourbook.export.DialogExportTour.okPressed(DialogExportTour.java:1311)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:468)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5895)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at net.tourbook.export.ExportTourTCX.exportTours(ExportTourTCX.java:49)
	at net.tourbook.extension.export.ActionExport$ActionExportTour.run(ActionExport.java:92)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5895)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1546)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1307)
	at org.eclipse.jface.action.ActionContributionItem.lambda$8(ActionContributionItem.java:1207)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5895)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at net.tourbook.application.Application.start(Application.java:35)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by wolfgang-ch** [comment]
> I repeated the test with the version which has the 23.10 tag in the git repo, now there are more errors and another dialog is displayed

When I lay in bed this morning at about 5:30am, I discovered the mistake I did with this test. I wanted to reproduce the dialog export tour error with this PR and not the old code 😮

**Comment by wolfgang-ch** [comment]
> I reproduced the issue and this is why the **Export Tours** dialog stays open.
> 
> It seems that [this line](https://github.com/mytourbook/mytourbook/blob/49b73da7a01d06cedafaaf2f83a4374814f04b96/bundles/net.tourbook.export/src/net/tourbook/export/DialogExportTour.java#L1453) from [your commit](https://github.com/mytourbook/mytourbook/commit/ad94f22cfd19e3b41458ac137a29b17ce158fdc5) is creating the NPE

Good catch which is fixed in https://github.com/mytourbook/mytourbook/commit/984fa014d9a0668ff95cf9791d6498058d048f0e

Now there is 1 remaining error 😄 


`Caused by: java.lang.IllegalArgumentException: EN_CH.keyboard not found, see http://wiki.eclipse.org/SWTBot/Keyboard_Layouts for more information.
`

[net.tourbook.ui.tests 20231024-072534.xml.zip](https://github.com/mytourbook/mytourbook/files/13111102/net.tourbook.ui.tests.20231024-072534.xml.zip)

**Comment by FJBDev** [comment]
> When I lay in bed this morning at about 5:30am, I discovered the mistake I did with this test. I wanted to reproduce the dialog export tour error with this PR and not the old code 😮

Ah, good to know that explains the failures that I couldn't reproduce

**Comment by FJBDev** [comment]
> Now there is 1 remaining error 😄
> 
> `Caused by: java.lang.IllegalArgumentException: EN_CH.keyboard not found, see http://wiki.eclipse.org/SWTBot/Keyboard_Layouts for more information. `
> 

I have [addressed that](https://github.com/FJBDev/mytourbook/pull/152/commits/e286318dd2a7be8d98090f125f56f4e832b7e9f2) in the PR now and it should work for you. At least it works locally and on the Github build (I didn't think of other people having different keyboards that it would affect SWTBot, yours seems to be swiss and SWTBot default didn't like that)

image

NOTE: However, even if the UI tests work most of the time, they can be brittle because they rely on other external processes that we don't have fully control over. For example, [this test](https://github.com/mytourbook/mytourbook/blob/197f21c34e03728832a415f9368eca43260750bb/bundles/net.tourbook.ui.tests/src/test/views/PoiViewTests.java#L32C11-L32C11) can fail because it uses internet results that sometimes take too long to come back even though I put a 5s wait.
So a good habit is sometimes that the tests must be run again to pass even though nothing was changed.
And also, [SWTBot ](https://projects.eclipse.org/projects/technology.swtbot)is not perfect and sometimes fails for no reason that I can explain

**Comment by wolfgang-ch** [comment]
Now with 0 errors 👍 

image

**Pull request merged**
