### PR TITLE
[Tour Nutrition] Bugfix for the computation of the average fluid per hour

### PR DESCRIPTION
**Pull request by FJBDev**

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
I've now finished 24.7, is it OK for you to start a test version?

**Comment by wolfgang-ch** [comment]
There are 4 strings which are not externalized

image

**Comment by FJBDev** [comment]
> I've now finished 24.7, is it OK for you to start a test version?

Yes, i am done with 24.7

**Comment by FJBDev** [comment]
> There are 4 strings which are not externalized
> 
> image

Ok, i will externalize them when i do the french translation for 24.7

**Pull request merged**
