### PR TITLE
Per code review

### PR DESCRIPTION
**Pull request by FJBDev**
@wolfgang-ch It is normal that the build fails because you will need to add this in your GitHub repo (you can see [it works](https://github.com/FJBDev/mytourbook/actions/runs/1391502493) on my repo with the same code)

> You're not authorized to run analysis. No sonar.login or SONAR_TOKEN env variable was set

Below are the steps

  1.  First of all, go to https://sonarcloud.io/, login with your GitHub account and enable the Sonar scan in your repository (more details [here](https://asus-aics.github.io/DeveloperGuide/pages/020_sonar_cloud/))

   2. After you enable Sonar scan, follow the steps and create new token called SONAR_TOKEN

   3. Copy the value of the token, go to your GitHub repository, click on Settings > Secrets and create a repository called SONAR_TOKEN with the value you have copied before
image

   4. Now the build should succeed

You can now also [customize ](https://sqa.stackexchange.com/questions/24734/how-to-deactivate-a-rule-in-sonarqube/36023#36023)the rules for SonarCloud :-)

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
@FJBDev 

When an issue like this...

image

... is set to resolved, is there a view to see all resolved issues, I did not find it ?

**Comment by FJBDev** [comment]
> ... is set to resolved, is there a view to see all resolved issues, I did not find it ?

If you go to this [view](https://sonarcloud.io/component_measures?id=wolfgang-ch_mytourbook&metric=false_positive_issues), you will be able to see all the "False Positive Issues" but also the Won't fix etc...

image

**Comment by wolfgang-ch** [comment]
First it looks very good but when I look into the file, I see a lot of unresolved issues but not the resolved issue

image

**Comment by FJBDev** [comment]
Ah, that was the wrong menu actually.
[Here](https://sonarcloud.io/project/issues?id=wolfgang-ch_mytourbook&resolutions=FALSE-POSITIVE) is the view where you can see all the resolved issued
(To access it from the main page:
- Click on the MT project.
- Then click on Main Branch.
- Then click on Issues.
- Scroll down and on the left hand side click on ‘Resolution’. Then click on ‘False Positive’)

image

And if you click on it, it will bring you to the file at the line of the resolved issue

image

**Comment by wolfgang-ch** [comment]
This new link helped :-)

I couldn't remember what I had solved

**Pull request merged**
