### PR TITLE
[JUnit] Test fixes for TCX, Suunto 9 file import and WeatherAPI

### PR DESCRIPTION
**Pull request by FJBDev**

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
When I run the tests with the current main, then Suunto 9 and TCX are failing because the markers are sorted differently as in your PR

```

net.tourbook.tests
device.suunto.Suunto9_DeviceDataReaderTests
testImportShoreLineWithLaps(device.suunto.Suunto9_DeviceDataReaderTests)
org.opentest4j.AssertionFailedError: tourMarkers[0].latitude
Expected: 40.581830140064625
     got: 40.58183912555793
 ; tourMarkers[0].longitude
Expected: -105.15960035499391
     got: -105.15969555265275
 ; tourMarkers[1].latitude
Expected: 40.58180512639406
     got: 40.58183062576696
 ; tourMarkers[1].longitude
Expected: -105.15970526669958
     got: -105.1596178402782
 ; tourMarkers[2].latitude
Expected: 40.58183345903062
     got: 40.581880410256915
 ; tourMarkers[2].longitude
Expected: -105.1596243163094
     got: -105.15968583860594
 ; tourMarkers[3].latitude
Expected: 40.58180026937065
     got: 40.58183912555793
 ; tourMarkers[3].longitude
Expected: -105.15970526669958
     got: -105.15963726837184
 ; tourMarkers[4].latitude
Expected: 40.5818360899183
     got: 40.58185126811645
 ; tourMarkers[4].longitude
Expected: -105.15960084069626
     got: -105.15968583860594
 ; tourMarkers[5].latitude
Expected: 40.581831840022815
     got: 40.55663845959625
 ; tourMarkers[5].longitude
Expected: -105.15967612455911
     got: -105.14383251419639
 ; tourMarkers[6].latitude
Expected: 40.58186341067498
     got: 40.581830140064625
 ; tourMarkers[6].longitude
Expected: -105.1596178402782
     got: -105.15960035499391
 ; tourMarkers[7].latitude
Expected: 40.581831840022815
     got: 40.58180512639406
 ; tourMarkers[7].longitude
Expected: -105.15969555265275
     got: -105.15970526669958
 ; tourMarkers[8].latitude
Expected: 40.581835887542326
     got: 40.58183345903062
 ; tourMarkers[8].longitude
Expected: -105.15960003119235
     got: -105.1596243163094
 ; tourMarkers[9].latitude
Expected: 40.5818245544877
     got: 40.58180026937065
 ; tourMarkers[9].longitude
Expected: -105.15969555265275
     got: -105.15970526669958
 ; tourMarkers[10].latitude
Expected: 40.581841554069634
     got: 40.5818360899183
 ; tourMarkers[10].longitude
Expected: -105.15958626962603
     got: -105.15960084069626
 ; tourMarkers[11].latitude
Expected: 40.581817268952584
     got: 40.581831840022815
 ; tourMarkers[11].longitude
Expected: -105.15968583860594
     got: -105.15967612455911
 ; tourMarkers[12].latitude
Expected: 40.581848839604746
     got: 40.58186341067498
 ; tourMarkers[13].longitude
Expected: -105.15970526669958
     got: -105.15969555265275
 ; tourMarkers[14].latitude
Expected: 40.58185450613206
     got: 40.581835887542326
 ; tourMarkers[14].longitude
Expected: -105.15958869813774
     got: -105.15960003119235
 ; tourMarkers[15].latitude
Expected: 40.58183912555793
     got: 40.5818245544877
 ; tourMarkers[16].latitude
Expected: 40.58183062576696
     got: 40.581841554069634
 ; tourMarkers[16].longitude
Expected: -105.1596178402782
     got: -105.15958626962603
 ; tourMarkers[17].latitude
Expected: 40.581880410256915
     got: 40.581817268952584
 ; tourMarkers[18].latitude
Expected: 40.58183912555793
     got: 40.581848839604746
 ; tourMarkers[18].longitude
Expected: -105.15963726837184
     got: -105.1596178402782
 ; tourMarkers[19].latitude
Expected: 40.58185126811645
     got: 40.581831840022815
 ; tourMarkers[19].longitude
Expected: -105.15968583860594
     got: -105.15970526669958
 ; tourMarkers[20].latitude
Expected: 40.55663845959625
     got: 40.58185450613206
 ; tourMarkers[20].longitude
Expected: -105.14383251419639
     got: -105.15958869813774
 ==> expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:214)
	at utils.Comparison.compareTourDataAgainstControl(Comparison.java:161)
	at device.suunto.Suunto9_DeviceDataReaderTests.testImportShoreLineWithLaps(Suunto9_DeviceDataReaderTests.java:173)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

device.garmin.GarminTCX_DeviceDataReaderTests
testTcxImportConeyLake(device.garmin.GarminTCX_DeviceDataReaderTests)
org.opentest4j.AssertionFailedError: tourMarkers[0].latitude
Expected: 40.135158
     got: 40.128272
 ; tourMarkers[0].longitude
Expected: -105.556992
     got: -105.592627
 ; tourMarkers[1].latitude
Expected: 40.136586
     got: 40.119869
 ; tourMarkers[1].longitude
Expected: -105.582931
     got: -105.608717
 ; tourMarkers[2].latitude
Expected: 40.136096
     got: 40.130077
 ; tourMarkers[2].longitude
Expected: -105.58185
     got: -105.589888
 ; tourMarkers[3].latitude
Expected: 40.128272
     got: 40.135158
 ; tourMarkers[3].longitude
Expected: -105.592627
     got: -105.556992
 ; tourMarkers[4].latitude
Expected: 40.119869
     got: 40.136586
 ; tourMarkers[4].longitude
Expected: -105.608717
     got: -105.582931
 ; tourMarkers[5].latitude
Expected: 40.130077
     got: 40.136096
 ; tourMarkers[5].longitude
Expected: -105.589888
     got: -105.58185
 ==> expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:214)
	at utils.Comparison.compareTourDataAgainstControl(Comparison.java:161)
	at utils.DeviceDataReaderTester.testImportFile(DeviceDataReaderTester.java:70)
	at device.garmin.GarminTCX_DeviceDataReaderTests.testTcxImportConeyLake(GarminTCX_DeviceDataReaderTests.java:34)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

```

**Comment by FJBDev** [comment]
> When I run the tests with the current main, then Suunto 9 and TCX are failing because the markers are sorted differently as in your PR
> 

Can you try to change [that ](https://github.com/mytourbook/mytourbook/blob/ac2049290f8c950156e1e72253721caf76fb8a18/bundles/net.tourbook.tests/src/test/utils/Comparison.java#L137C19-L137C34)to `LENIENT` and see if it still fails ?

See the different values [here](http://jsonassert.skyscreamer.org/javadoc/org/skyscreamer/jsonassert/JSONCompareMode.html)

**Comment by wolfgang-ch** [comment]
I just discovered your last comment but the change to `LENIENT` do not solve the problem

image

**Comment by FJBDev** [comment]
> I just discovered your last comment but the change to `LENIENT` do not solve the problem
> 
I'll see what I can find locally but so far, it works perfectly on [GitHub](https://github.com/mytourbook/mytourbook/actions/runs/10157989719)

**Pull request merged**
