### PR TITLE
[UI Tests] Improvements and additions

### PR DESCRIPTION
**Pull request by FJBDev**
- Adding UI tests for the statistics view
- Changed the build to upload MT's screenshots and logs to the build when the UI tests fail to help troubleshooting in the future
Example with the statistics view and marker view tests failing:

image

[UI-Tests-Failures-Artifacts.zip](https://github.com/FJBDev/mytourbook/files/9261832/UI-Tests-Failures-Artifacts.zip)

@wolfgang-ch 
While working with artifacts, I've noticed that other Github repos are using Artifacts and Assets to store the program executables to be downloaded from the users (releases, nightly builds....etc).
Now that you've moved the feature requests from SourceForge, it seems that if you move the executables as [Assets ](https://docs.github.com/en/rest/releases/assets)in Github, the MT's project will be fully on Github or maybe you prefer having the executables on SF ?

Example with [WorldWindJava releases](https://github.com/NASAWorldWind/WorldWindJava/releases/tag/v2.2.1)

image

### CODE REVIEW

**Comment by wolfgang-ch** [comment]
> Now that you've moved the feature requests from SourceForge, it seems that if you move the executables as [Assets ](https://docs.github.com/en/rest/releases/assets)in Github, the MT's project will be fully on Github or maybe you prefer having the executables on SF ?

I've put the last update sites to GitHub because it was easier to manage for me but I want to keep the MT executables on SF to also have contiuous download statistics and the workflow to upload files is relative easy:

* Create new folder on SF
* Upload files with Filezilla
* Set OS flags on SF

Does GitHub provide download statistics?

**Comment by wolfgang-ch** [comment]
You should not edit a comment which is referencing me, I don't receive a notifications for the edits. I saw `@wolfgang-ch` just by accident

image

**Comment by FJBDev** [comment]
> Does GitHub provide download statistics?

There are some [extra tools ](https://github.com/qishibo/github-release-statistics)that seem to provide statistics but I don't see Github supporting stats natively. Maybe SF statistics are better at this point

**Comment by FJBDev** [comment]
> You should not edit a comment which is referencing me, I don't receive a notifications for the edits. I saw `@wolfgang-ch` just by accident
> 
Good to know

**Pull request merged**
