### PR TITLE
Fix for unit tests #499

### PR DESCRIPTION
**Pull request by FJBDev**

### CODE REVIEW

**Comment by FJBDev** [comment]
@wolfgang-ch This fixes the current unit tests issues though I am not sure why this is needed as it was working before you implemented the new `.mt` format. Maybe you know more.

**Comment by wolfgang-ch** [comment]
> @wolfgang-ch This fixes the current unit tests issues though I am not sure why this is needed as it was working before you implemented the new `.mt` format. Maybe you know more.

Not much, I just added some/many get/set methods for direct access to the class fields and `SerieData` which you have fixed.

**Comment by wolfgang-ch** [comment]
Link to this issue https://github.com/mytourbook/mytourbook/issues/499

**Comment by FJBDev** [comment]
> Link to this issue #499

I will let you close the issue when you merge this fix to `main`. Note that I tried it on my repo and the [build succeeded](https://github.com/FJBDev/mytourbook/actions/runs/2066190889)

**Pull request merged**
